services:
    admin.article:
        class: Unrtech\ContentBundle\Admin\ArticleAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "general.articles", label: "general.articles", label_catalogue: "admin" }
        arguments:
            - ~
            - Unrtech\ContentBundle\Entity\Article
            - 'UnrtechContentBundle:CRUD'
    admin.seo:
        class: Unrtech\ContentBundle\Admin\SeoAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "general.reference", label: "general.seo", label_catalogue: "admin" }
        arguments:
            - ~
            - Unrtech\ContentBundle\Entity\Seo
            - 'UnrtechContentBundle:CRUD'