imports:
    - { resource: admin.yml }
services:
    admin.helper:
        class: Unrtech\ContentBundle\Helper\AdminHelper
        arguments: [ @doctrine.orm.default_entity_manager, @security.token_storage, @translator.default ]
#    unrtech_content.example:
#        class: Unrtech\ContentBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
